cogitoweb_pentaho_proxy:
    path:       /report/{id}
    defaults:   { _controller: CogitowebPentahoProxyBundle:Default:proxy }
    requirements:
        id: \d+
        
cogitoweb_pentaho_require_parameters:
    path:       /report/{id}/complete-parameters
    defaults:   { _controller: CogitowebPentahoProxyBundle:Default:requireParameters }
    requirements:
        id: \d+